'''
Code to classify cells as infected or non-infected based on predicted infection and center masks produced by VAIruScope (inference.py). Marks centers on BF/PC images and writes
summary counts to numbers.txt.
'''
# import libraries and modules
import os
import re
from typing import Dict, List, Optional, Tuple

import cv2
import numpy as np
from tqdm import tqdm

# -----------------------------
# Configuration
# -----------------------------
intensity_threshold=0.5  #mean ROI intensity above this => cell is infected
center_thresh=5          #threshold on center mask to detect peaks
box_size=5               #ROI size around center (pixels)
half_box = box_size // 2 #distance to measure box intensity

#directories
bf_path= ".../VAIruScope/example_images/" #path to folder with BF/PC images
pred_path = ".../VAIruScope/inference/" #path to folder with raw model inference output (generated by inference.py)
save_path = ".../VAIruScope/pred_infection/" #path to the folder where images with predicted infected/non-infected cells should be saved
os.makedirs(save_path, exist_ok=True)

# -----------------------------
# Functions
# -----------------------------
def compute_centers_from_center_image(
    center_image: np.ndarray,
    thresh: int = center_thresh,
    kernel: Optional[np.ndarray] = None,
    dilate_iterations: int = 1,
    connectivity: int = 8,
) -> List[List[int]]:
    """
    compute center coordinates from center mask.
    returns list of (cx, cy) in pixel coordinates.
    """
    if center_image is None:
        raise ValueError("center_image is None (failed to load?)")

    if kernel is None:
        kernel = np.array(
            [[0, 1, 1, 1, 0],
             [1, 1, 1, 1, 1],
             [1, 1, 1, 1, 1],
             [1, 1, 1, 1, 1],
             [0, 1, 1, 1, 0]],
            dtype=np.uint8
        )

    img = center_image
    # Binary mask of peaks
    binary = (img > thresh).astype(np.uint8)

    # Dilate the *binary* mask (safe)
    if dilate_iterations > 0:
        binary = cv2.dilate(binary, kernel, iterations=dilate_iterations)

    # Connected components + centroids
    n_labels, labels, stats, centroids = cv2.connectedComponentsWithStats(
        binary, connectivity=connectivity
    )

    # centroids: (label, 2) as (x, y); label 0 is background
    centers = [[int(x), int(y)] for (x, y) in centroids[1:]]  # skip background
    return centers

def get_infected_cells(bf_file):
    """
    Process one BF file:
    - load BF, infection mask, center mask
    - compute centers
    - measure infection ROI mean per center
    - draw markers
    - write marked BF image
    """
    if not bf_file.lower().endswith('.tif'):
        return

    pred_infection_file     = bf_file.replace('.tif', '_infection.tif')
    pred_center_file        = bf_file.replace('.tif', '_center.tif')

    bf = cv2.imread(os.path.join(bf_path, bf_file), cv2.IMREAD_UNCHANGED)
    if bf is None:
        return

    bf = cv2.normalize(bf, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)
    bf = cv2.cvtColor(bf, cv2.COLOR_BGR2RGB)

    infection_img = cv2.imread(os.path.join(pred_path, pred_infection_file), cv2.IMREAD_UNCHANGED)
    if infection_img is None:
        return

    center_img = cv2.imread(os.path.join(pred_path, pred_center_file), cv2.IMREAD_UNCHANGED)
    if center_img is None:
        return

    centers = compute_centers_from_center_image(center_img, thresh=center_thresh)

    H, W = infection_img.shape[:2]
    for i, (cx, cy) in enumerate(centers):
        xmin = max(cx - half_box, 0); ymin = max(cy - half_box, 0)
        xmax = min(cx + half_box + 1, W); ymax = min(cy + half_box + 1, H)

        roi = infection_img[ymin:ymax, xmin:xmax]
        if roi.size == 0:
            continue

        mean_val = float(np.mean(roi))
        infected = mean_val > intensity_threshold
        status = 'infected' if infected else 'non_infected'

        color = (0, 255, 0) if infected else (255, 0, 0)
        cv2.drawMarker(
            bf, (cx, cy), color,
            markerType=cv2.MARKER_TILTED_CROSS,
            markerSize=25, thickness=2, line_type=cv2.LINE_AA
        )

    cv2.imwrite(os.path.join(save_path, bf_file), bf)

def main():
    bf_files = sorted(os.listdir(bf_path))

    for bf_file in tqdm(bf_files, desc="Processing images", unit="img"):
        get_infected_cells(bf_file)

    print("The infection predictions were successfully saved at", save_path)

if __name__ == "__main__":
    main()
