'''
Code to classify cells as infected or non-infected based on predicted infection and center masks produced by VAIruScope (inference.py). Marks centers on BF/PC images and writes
summary counts to numbers.txt.
'''
# import libraries and modules
import os
import re
from typing import Dict, List, Optional, Tuple

import cv2
import numpy as np
from tqdm import tqdm

# -----------------------------
# Configuration
# -----------------------------
intensity_threshold=0.5  #mean ROI intensity above this => cell is infected
center_thresh=5          #threshold on center mask to detect peaks
box_size=5               #ROI size around center (pixels)
half_box = box_size // 2 #distance to measure box intensity

#directories
bf_path= "/home/pfeilj/scratch/VAIruScope/example_images/" #path to folder with BF/PC images
pred_path = "/home/pfeilj/scratch/VAIruScope/inference/" #path to folder with raw model inference output (generated by inference.py)
save_path = "/home/pfeilj/scratch/VAIruScope/pred_infection/" #path to the folder where images with predicted infected/non-infected cells should be saved
os.makedirs(save_path, exist_ok=True)

#concentration patterns in file names
negative_string=r'Mock'
low_concentration=r'Low'
middle_concentration=r'Middle'
high_concentration=r'High'

display_names = {
    'mock': negative_string,
    'low': low_concentration,
    'middle': middle_concentration,
    'high': high_concentration,
}

days = ['total'] + [f'Day{i}' for i in range(1, 8)]
day_strings = {f'Day{i}': f'Day{i}' for i in range(1, 8)}
states = ['mock', 'low', 'middle', 'high']
infection_status = ['infected', 'non_infected']
data = {day: {state: {status: 0 for status in infection_status} for state in states} for day in days}

# -----------------------------
# Functions
# -----------------------------
def get_day(name):
    """Extract 'Day1'...'Day7' from filename."""
    for day_str, day_key in day_strings.items():
        if day_key in name:
            return day_key
    return None

def get_concentration(name):
    """Map filename to internal concentration label."""
    if re.search(negative_string, name):
        return 'mock'
    if re.search(low_concentration, name):
        return 'low'
    if re.search(middle_concentration, name):
        return 'middle'
    if re.search(high_concentration, name):
        return 'high'
    return None

def compute_centers_from_center_image(
    center_image: np.ndarray,
    thresh: int = center_thresh,
    kernel: Optional[np.ndarray] = None,
    dilate_iterations: int = 1,
    connectivity: int = 8,
) -> List[List[int]]:
    """
    compute center coordinates from center mask.
    returns list of (cx, cy) in pixel coordinates.
    """
    if center_image is None:
        raise ValueError("center_image is None (failed to load?)")

    if kernel is None:
        kernel = np.array(
            [[0, 1, 1, 1, 0],
             [1, 1, 1, 1, 1],
             [1, 1, 1, 1, 1],
             [1, 1, 1, 1, 1],
             [0, 1, 1, 1, 0]],
            dtype=np.uint8
        )

    img = center_image
    # Binary mask of peaks
    binary = (img > thresh).astype(np.uint8)

    # Dilate the *binary* mask (safe)
    if dilate_iterations > 0:
        binary = cv2.dilate(binary, kernel, iterations=dilate_iterations)

    # Connected components + centroids
    n_labels, labels, stats, centroids = cv2.connectedComponentsWithStats(
        binary, connectivity=connectivity
    )

    # centroids: (label, 2) as (x, y); label 0 is background
    centers = [[int(x), int(y)] for (x, y) in centroids[1:]]  # skip background
    return centers

def process_one_image(bf_file):
    """
    Process one BF file:
    - load BF, egfp, center mask
    - compute centers
    - measure egfp ROI mean per center
    - draw markers
    - update 'data' counters
    - write marked BF image
    """
    if not bf_file.lower().endswith('.tif'):
        return

    pred_eGFP_file   = bf_file.replace('.tif', '_egfp.tif')
    pred_center_file = bf_file.replace('.tif', '_center.tif')

    bf = cv2.imread(os.path.join(bf_path, bf_file), cv2.IMREAD_UNCHANGED)
    if bf is None:
        return

    bf = cv2.normalize(bf, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)
    bf = cv2.cvtColor(bf, cv2.COLOR_BGR2RGB)  # (kept exactly as in your code)

    egfp = cv2.imread(os.path.join(pred_path, pred_eGFP_file), cv2.IMREAD_UNCHANGED)
    if egfp is None:
        return

    center_img = cv2.imread(os.path.join(pred_path, pred_center_file), cv2.IMREAD_UNCHANGED)
    if center_img is None:
        return

    centers = compute_centers_from_center_image(center_img, thresh=center_thresh)

    concentration = get_concentration(pred_eGFP_file)
    if not concentration:
        cv2.imwrite(os.path.join(save_path, bf_file), bf)
        return

    day = get_day(pred_eGFP_file)

    H, W = egfp.shape[:2]
    for i, (cx, cy) in enumerate(centers):
        xmin = max(cx - half_box, 0); ymin = max(cy - half_box, 0)
        xmax = min(cx + half_box + 1, W); ymax = min(cy + half_box + 1, H)

        roi = egfp[ymin:ymax, xmin:xmax]
        if roi.size == 0:
            continue

        mean_val = float(np.mean(roi))
        infected = mean_val > intensity_threshold
        status = 'infected' if infected else 'non_infected'

        color = (0, 255, 0) if infected else (255, 0, 0)
        cv2.drawMarker(
            bf, (cx, cy), color,
            markerType=cv2.MARKER_TILTED_CROSS,
            markerSize=25, thickness=2, line_type=cv2.LINE_AA
        )

        data['total'][concentration][status] += 1
        if day:
            data[day][concentration][status] += 1

    cv2.imwrite(os.path.join(save_path, bf_file), bf)

def write_numbers_txt(file_path):
    """Write the summary counts in 'data' to numbers.txt."""
    with open(file_path, "w") as f:
        f.write('concentration\ti\tn\n\n')

        for conc_internal, conc_display in display_names.items():
            f.write(f'{conc_display}\n')

            total_infected = data['total'][conc_internal]['infected']
            total_not_infected = data['total'][conc_internal]['non_infected']
            f.write(f'Total\t{total_infected}\t{total_not_infected}\n')

            for day in [f'Day{i}' for i in range(1, 8)]:
                infected_count = data[day][conc_internal]['infected']
                not_infected_count = data[day][conc_internal]['non_infected']
                f.write(f'{day}\t{infected_count}\t{not_infected_count}\n')

            f.write('\n')

def main():
    bf_files = sorted(os.listdir(bf_path))

    for bf_file in tqdm(bf_files, desc="Processing images", unit="img"):
        process_one_image(bf_file)

    print("The infection predictions were successfully saved at", save_path)

    file_path = os.path.join(save_path, "numbers.txt")
    write_numbers_txt(file_path)

    print("The counting results were successfully written to numbers.txt at", file_path)

if __name__ == "__main__":
    main()